language: php
php:
- 7.1
matrix:
  fast_finish: true
services:
- mysql
env:
- SYMFONY_VERSION="3.2.*" DB=mysql
cache:
  directories:
  - vendor
before_install:
- openssl aes-256-cbc -K $encrypted_c37cded0adbe_key -iv $encrypted_c37cded0adbe_iv -in .travis.tar.enc -out .travis.tar -d
- tar xf .travis.tar
- composer self-update
- perl .travis/gdown.pl https://docs.google.com/uc\?export\=download\&id\=0B94z-_1TYap3VHYzSk1ueEU0YzA src/AppBundle/Resources/data/fixtures/Post_Adressdaten.csv
install:
- composer install
- mkdir -p build/logs/
- php bin/console doctrine:database:create --env=test
- php bin/console doctrine:schema:create --env=test
script:
- vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
after_success:
- travis_retry php vendor/bin/coveralls -v
- travis_retry php vendor/bin/codacycoverage clover
notifications:
  slack:
    secure: 1vDIwgE2dzLfmPihg7PnVHnBfd6zkJfOMm++njGqgb+cuAUuRjXTDcqh0DXZn3N3OqjEKgXrUY4ShgDyoY/6CVQ9LqPPY1tsPxhRLEIKCvqHUoCbe46AK5r9opYQTA5qkBP8Mz+0JpepjFqWRoM2iGP9dBOBpMxFfB6PNb9+9Rln358WnpoVV2xaGFotwLqrRVXWEacCGFL3DMe5ECi7C/A0xaNSzYFvw5nyDVfpGSlqHJprbBkg2nhkVLWn2rF+lTyM5dyTaLNSWAYhffYXhUNvIcT8wWcIym37KGrai/CPvrKdDaLJAhsSP5JHKPeITrpqXeUUI4NXn9+iHPcGS38xnHhCfrbeeQezM5DF0MOuVRePZvzozt7mG5GOns1Xcfoxh2CWIth5AhKogp1mryP3aelNPWEJoBVoDOSO0CLRN7NbPYxJunrdVi0pSKcFRu6DVDj37qYGS7E4SnsazTLqTp4uD2fww1Bijb/Q1Los29l2+nglELW4acUJ86kRxpG2qn+tY98WVi4/qsXBDMOgz9DoqdFvrhgerSJ7NChoPgKMtdHZ5cwdwqE5a6cxDgZcO5exEBYENiN2/6YjtTFLNCLoH6IecApxMrsv2mMun4Lwm2CG84G/AwB3ROFWilXopKxcX+zYlTEaIxIEg15oMJctjGa7AXEjFPndpqs=
