language: php

php:
  - 7.1

matrix:
  fast_finish: true

services:
  - mysql

env:
  - SYMFONY_VERSION="3.2.*" DB=mysql

before_install:
  - openssl aes-256-cbc -K $encrypted_c37cded0adbe_key -iv $encrypted_c37cded0adbe_iv -in .travis.tar.enc -out .travis.tar -d
  - tar xf .travis.tar
  - composer self-update
  - echo before-install

install:
  - composer install
  - mkdir -p build/logs/
  - mkdir -p web/build/
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test

script:
  - phpunit

after_success:
  - travis_retry php vendor/bin/coveralls -v
