<?php

namespace AppBundle\Repository;

/**
 * TalentStatusRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TalentStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
