# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    role_hierarchy:
        ROLE_ADMIN:     [ROLE_SCOUT]
        ROLE_SCOUT:     [ROLE_TALENT]
        ROLE_TALENT:    [ROLE_USER]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        google:
            entity:
                class: AppBundle:User
                property: accessToken

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout:
                path: /logout

            guard:
                authenticators:
                    - app.security.gogole_authenticator

            form_login:
                login_path: /login
                check_path: /login

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
