# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.security.gogole_authenticator:
        class: AppBundle\Security\GoogleAuthenticator
    app.service.google:
        class: AppBundle\Service\GoogleService
        arguments: ['@kernel']
    app.service.google.user:
        class: AppBundle\Service\GoogleUserService
        arguments: ['@kernel', '@doctrine.orm.entity_manager']
    app.service.portfolio.pdf:
        class: AppBundle\Service\PortfolioPdfService
        arguments: ['@doctrine.orm.default_entity_manager', '@white_october.tcpdf']
    app.service.person_pic_uploader:
            class: AppBundle\Service\FileUploadService
            arguments: ['%person_pic_location%']
    app.twig_extension.person:
        class: AppBundle\Twig\Extension\PersonTwigExtension
        public: false
        tags:
            - {name: twig.extension}
