# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.security.gogole_authenticator:
        class: AppBundle\Security\GoogleAuthenticator
    app.helper.google:
        class: AppBundle\Helper\GoogleHelper
        arguments: ['@kernel', '%google_apps_admin%', '@doctrine.orm.entity_manager']

