# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.security.gogole_authenticator:
        class: AppBundle\Security\GoogleAuthenticator
    app.service.google:
        class: AppBundle\Service\GoogleService
        arguments: ['@kernel', '@doctrine.orm.entity_manager']
    app.service.google.user:
        class: AppBundle\Service\GoogleUserService
        arguments: ['@kernel', '@doctrine.orm.entity_manager']
