#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd $DIR/nginx
docker build -t ictscouts/nginx:$1 -t ictscouts/nginx:latest .
docker push ictscouts/nginx:$1
docker push ictscouts/nginx:latest

cd $DIR/php
docker build -t ictscouts/php:$1 -t ictscouts/php:latest .
docker push ictscouts/php:$1
docker push ictscouts/php:latest